### ISSUE TITLE
Need to set あ to path on 16px icon.

### ISSUE THREAD

**Issue by micahilbery** [aggalex/Nihongo#1]
![img_20180107_132333](https://user-images.githubusercontent.com/10608836/34653325-12a5363e-f3b0-11e7-8626-9b98b9fa4836.jpg)

**Comment by aggalex** [comment]
Whoopsie daisy, what a forgetful man I am! I will fix this tomorrow evening.

> _This is the first bug report that I receive on Github & I'm super duper excited!_

**Comment by aggalex** [comment]
Done!
